<?php

/**
 * @file
 * Contains citywidgets.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function citywidgets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the citywidgets module.
    case 'help.page.citywidgets':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a set of city widgets') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function citywidgets_theme($existing, $type, $theme, $path) {
  return [
    'citywidgets_weather_widget' => [
      'variables' => ['city' => NULL, 'temperature' => NULL],
    ],
  ];
}

